spring:
  datasource:
    url: jdbc:h2:file:./crrs-db
    username: 'sa'
    password:
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
    console:
      path: '/console'
  jpa:
    hibernate:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
      ddl-auto: update
      show-sql: true
      format_sql: true
      use_sql_comments: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

values:
  reservation:
    minimum.time.reservation.in.minutes: 15
    maximum.time.reservation.in.minutes: 120

